quarkus.datasource.devservices.enabled=false

# PostgreSQL Datasource Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
# quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/quarkus?currentSchema=quarkus-playground
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://postgres:5432/quarkus?currentSchema=quarkus-playground}
quarkus.datasource.jdbc.max-size=20

# Hibernate ORM Configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.sql-load-script=import.sql